env:
  browser: true
  es2021: true
  jest: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  import/extensions: off,
  import/prefer-default-export: off
}
